# Lab 1 - Digital Image Processing
## Matrix Addition and Multiplication
## Bahria University Islamabad

**Name:** Saadat Hussain  
**Enrolment:** 01-134211-078  
**Class-Section:** BSCS 7-B  

#### Importing Dependencies

In [1]:
import numpy as np

### Task 1 - Matrix Addition
Write a Python program that adds two matrices provided by the user. The program should ask for the dimensions of the matrices and ensure that they have the same dimensions before performing the addition. 

In [2]:
# Dimensions input for matrices
def input_dimensions():
    rows = int(input("Enter # of rows:"))
    columns = int(input("Enter # of columns:"))
    return rows, columns

# Elements input
def input_elements(rows, cols, name):
    print(f"Enter elements for {name}:")
    matrix = [] #empty matrix which must be appended after user inputs elements
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i}][{j}]: "))
            row.append(element)
        matrix.append(row)
    return np.array(matrix)

# Matrix Addition
def matrix_addition(matrix_a, matrix_b):\
    #check if matrix addition possible using shape function
    if matrix_a.shape != matrix_b.shape:
        return "Matrix Addition is not possible as both matrices have different dimensions."
    rows, cols = matrix_a.shape
    result = np.zeros((rows,cols)) #Initializing Resultant Matrix with Zeros
    for i in range(rows): # nested for loop to traverse matrix
        for j in range(cols): 
            result[i][j] = matrix_a[i][j] + matrix_b[i][j] #Element wise addtion
    return result
    
    

In [4]:
## Driver Cell

print("For Matrix A:")
rows_a, cols_a = input_dimensions()
matrix_a = input_elements(rows_a, cols_a, "Matrix A")

print("\nFor Matrix B:")
rows_b, cols_b = input_dimensions()
matrix_b = input_elements(rows_b, cols_b, "Matrix B")

result = matrix_addition(matrix_a, matrix_b)

print("Result = \n", result)

For Matrix A:


Enter # of rows: 3
Enter # of columns: 3


Enter elements for Matrix A:


Enter element [0][0]:  1
Enter element [0][1]:  2
Enter element [0][2]:  3
Enter element [1][0]:  4
Enter element [1][1]:  5
Enter element [1][2]:  6
Enter element [2][0]:  7
Enter element [2][1]:  8
Enter element [2][2]:  9



For Matrix B:


Enter # of rows: 3
Enter # of columns: 3


Enter elements for Matrix B:


Enter element [0][0]:  9
Enter element [0][1]:  8
Enter element [0][2]:  7
Enter element [1][0]:  6
Enter element [1][1]:  5
Enter element [1][2]:  4
Enter element [2][0]:  3
Enter element [2][1]:  2
Enter element [2][2]:  1


Result = 
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


### Task 2 - Matrix Multiplication
Write a Python program to multiply two matrices provided by the user. The program should check if the number of columns in the first matrix is equal to the number of rows in the second matrix.


In [5]:
# Dimensions input for matrices
def input_dimensions():
    rows = int(input("Enter # of rows:"))
    columns = int(input("Enter # of columns:"))
    return rows, columns

# Elements input
def input_elements(rows, cols, name):
    print(f"Enter elements for {name}:")
    matrix = [] #empty matrix which must be appended after user inputs elements
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i}][{j}]: "))
            row.append(element)
        matrix.append(row)
    return np.array(matrix)

# Matrix Multiplication
def matrix_multiplication(matrix_a, matrix_b):
    if len(matrix_a[0]) != len(matrix_b):
        return "Matrix multiplication is not possible as the number of columns in the first matrix does not match the number of rows in the second matrix."
    
    result = []
    for i in range(len(matrix_a)):
        row = []
        for j in range(len(matrix_b[0])):
            row.append(0)
        result.append(row)
    
    for i in range(len(matrix_a)):
        for j in range(len(matrix_b[0])):
            for k in range(len(matrix_b)):
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]
    return result

In [6]:
# Driver Code
print("For Matrix A:")
rows_a, cols_a = input_dimensions()
matrix_a = input_elements(rows_a, cols_a, "Matrix A")

print("\nFor Matrix B:")
rows_b, cols_b = input_dimensions()
matrix_b = input_elements(rows_b, cols_b, "Matrix B")

result = matrix_multiplication(matrix_a, matrix_b)
print("Result = \n", result)

For Matrix A:


Enter # of rows: 2
Enter # of columns: 2


Enter elements for Matrix A:


Enter element [0][0]:  2
Enter element [0][1]:  4
Enter element [1][0]:  1
Enter element [1][1]:  2



For Matrix B:


Enter # of rows: 2
Enter # of columns: 4


Enter elements for Matrix B:


Enter element [0][0]:  1
Enter element [0][1]:  2
Enter element [0][2]:  3
Enter element [0][3]:  4
Enter element [1][0]:  5
Enter element [1][1]:  6
Enter element [1][2]:  7
Enter element [1][3]:  8


Result = 
 [[22.0, 28.0, 34.0, 40.0], [11.0, 14.0, 17.0, 20.0]]
